language: java
jdk:
- oraclejdk8
script: mvn clean test package
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: Mje+Cgc25Eoa2+d6Fo8+ZxZkgO9x7Z8NLazrBMFc7N8hYQpLvFeMTxiyxm0OxsILuCRSYZBcEu4XMCmohmnvCUAkPmqfl/QLexRA8MDyLvhkHt2MW1QPRdgb+raCi1LZ87cep51lzMF+7Vivl0hJHFqtDYIjTIu2usJ5J+YgsSBvEwL6wizZcCmNw88XOmfksC7W0es9pMPkiAC2riBe0rTlxYQ+gtP8RjZpP1kmJgYpPLC1xkgiYrMstnFnCGBANldbJO+BWVGGLeCKMaYBfqX6dKX2xv2bERmfZOwfFn/ZfIA7ICf/8I/ZheBn2sWQi/0PXaCUXwW1LKFiMHpda1SA/4joUrJIylpUoo3nH+mrMUNDosTX3rHTFycAwYGHeSIk0ntiiROpfMUeJIlFhDwlYckjNyAwcksR2cefeiML8936wbmWxyWcJEXXzCAHOmmgfOqFrYk/ejB2C0SMM3SORlyBWUeWXPu7llXFDSMdeq6dPAs+fKtginJ8ma84QeIJdZ+p/FXsSAP60ccLQh1GdcUj7vmzqRt+ikzRc/BXuAVV820zZqiivBEU/1exKeSYetyDgDbuLfxuFKIPcz86MOVnaoUsy8feo+azAKBNqnp6quz5Fv6tIiv+I8cjkbByNm0I6N9FLk4TcphvJ/vb+iNQV8GHyP7Ktj07gLA=
  file_glob: true
  file: "target/eltermc-plugin*.jar"
  skip_cleanup: true
  on:
    repo: enolgor/eltermc-plugin
    tags: true
    branches:
      only:
        - master